ecg_balancing/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from ecg_balancing.forms import UserAccountCreationForm
from django.conf.urls.defaults import url, patterns
from wkhtmltopdf.views import PDFTemplateView

from ecg_balancing.views import *

admin.autodiscover()


urlpatterns = patterns('',

	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'ecg_balancing/registration/login.html'}, name='login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'ecg_balancing/registration/logout.html'}, name='logout'),
    url(r'^accounts/profile/$', UserDetailRedirect.as_view(url=reverse_lazy('user-detail'))),
    url(r'^accounts/register/$', UserCreateView.as_view(
        template_name='ecg_balancing/registration/register.html', form_class=UserAccountCreationForm, success_url='reverse("user-detail")'), name='register'),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'ecg_balancing/registration/password_email_form.html'}, name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'ecg_balancing/registration/password_email_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'ecg_balancing/registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'ecg_balancing/registration/password_reset_done.html'}, name='password_reset_complete'),

    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'ecg_balancing/registration/password_change_form.html'}, name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'ecg_balancing/registration/password_change_done.html'}, name='password_change_done'),


	url(r'^user/(?P<pk>.*)/$', login_required(UserDetailView.as_view()), name='user-detail'),
	url(r'^user/(?P<pk>.*)/update/$', login_required(UserUpdateView.as_view()), name='user-update'),

	url(r'^c/$', CompanyListView.as_view(), name='companies'),
	url(r'^c/admin/$', permission_required('is_staff')(CompaniesAdminView.as_view()), name='companies-admin'),
	url(r'^c/join/$', login_required(CompanyJoinView.as_view()), name='company-join'),
	url(r'^c/create/$', login_required(CompanyCreateView.as_view()), name='company-create'),

	url(r'^c/(?P<slug>[\w-]*)/$', CompanyDetailView.as_view(), name='company-detail'),
	url(r'^c/(?P<slug>[\w-]*)/update$', login_required(CompanyUpdateView.as_view()), name='company-update'),
	url(r'^c/(?P<slug>[\w-]*)/admin$', login_required(CompanyAdminView.as_view()), name='company-admin'),

    #url(r'^i/create$', login_required(CompanyBalanceIndicatorCreateView.as_view()), name='indicator-create'),
    url(r'^b/(?P<company_slug>[\w-]*)/(?P<balance_id>[0-9]*)/(?P<indicator_id>[a-z][0-9]*)/$', CompanyBalanceIndicatorUpdateView.as_view(), name='indicator-update'),
    #url(r'^b/(?P<company_slug>[\w-]*)/(?P<pk>[\d]*)/update/$', login_required(CompanyBalanceIndicatorUpdateView.as_view()), name='indicator-update'),

	url(r'^b/(?P<company_slug>.*)/create/$', login_required(CompanyBalanceCreateView.as_view()), name='balance-create'),
	url(r'^b/(?P<company_slug>.*)/(?P<pk>[0-9]*)/$', CompanyBalanceDetailView.as_view(), name='balance-detail'),
    url(r'^b/(?P<company_slug>.*)/(?P<pk>[0-9]*)/update/$', login_required(CompanyBalanceUpdateView.as_view()), name='balance-update'),
	url(r'^b/(?P<company_slug>.*)/(?P<pk>[0-9]*)/export/$', login_required(CompanyBalanceExportView.as_view()), name='balance-export'),


    url(r'^feedback/indicator/(?P<indicator_id>[\w.]*)/$', login_required(FeedbackIndicatorFormView.as_view()), name='feedback-indicator'),
    url(r'^feedback/success/$', login_required(FeedbackIndicatorSuccessView.as_view()), name='feedback-indicator-success'),

    (r'^ckeditor/', include('ckeditor.urls')),

    # leave at the end
    url(r'^select2/', include('django_select2.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^', include('cms.urls')),
)

ecg_balancing/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
import urllib
import urllib2
import simplejson

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.db.models import signals
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

from ecg_balancing import fields


# -------------------------------- MATRIX MODELS --------------------------------
from ecg_balancing.managers import CompanyBalanceIndicatorManager, CompanyManager

MATRIX_VERSION_4_1 = '4.1'
MATRIX_VERSIONS = (
    (MATRIX_VERSION_4_1, MATRIX_VERSION_4_1),
)

STAKEHOLDERS = (
    ('a', _('Suppliers')),
    ('b', _('Investors')),
    ('c', _('Employees, including business owners')),
    ('d', _('Customers, Products, Services, Business Partners')),
    ('e', _('Social Environment: Region, electorate, future generations, civil society, fellow human beings, animals and plants')),
    ('n', _('Negative Criteria')),
)


class ECGMatrix(models.Model):
    version = models.CharField(_('Version'), max_length=6, choices=MATRIX_VERSIONS,
                                      default=MATRIX_VERSION_4_1)
    contact = models.EmailField(_('Email'))

    class Meta:
        verbose_name = _('Matrix')
        verbose_name_plural = _('Matrices')

    def __unicode__(self):
        return self.version


class Indicator(models.Model):
    ECG_VALUE_1 = '1'
    ECG_VALUE_2 = '2'
    ECG_VALUE_3 = '3'
    ECG_VALUE_4 = '4'
    ECG_VALUE_5 = '5'
    ECG_VALUES = (
        (ECG_VALUE_1, _('Human Dignity')),
        (ECG_VALUE_2, _('Cooperation and Solidarity')),
        (ECG_VALUE_3, _('Ecological Sustainability')),
        (ECG_VALUE_4, _('Social Justice')),
        (ECG_VALUE_5, _('Democratic Co-determination and Transparency')),
    )
    RELEVANCE_HIGH = 'high'
    RELEVANCE_MIDDLE = 'middle'
    RELEVANCE_LOW = 'low'
    RELEVANCE_NONE = 'none'
    RELEVANCE_VALUES = (
        (RELEVANCE_HIGH, _('High')),
        (RELEVANCE_MIDDLE, _('Middle')),
        (RELEVANCE_LOW, _('Low')),
        (RELEVANCE_NONE, _('Doesn''t match'))
    )
    RELEVANCE_MAPPING = {
        RELEVANCE_HIGH: 3,
        RELEVANCE_MIDDLE: 2,
        RELEVANCE_LOW: 1,
        RELEVANCE_NONE: 0,
    }

    matrix = models.ForeignKey('ecg_balancing.ECGMatrix', verbose_name=_(u'Matrix'), related_name='indicators',
                              null=False,
                              blank=False)

    title = models.CharField(_('Name'), max_length=255)
    stakeholder = models.CharField(_('Stakeholder'), max_length=1, choices=STAKEHOLDERS)
    ecg_value = models.CharField(_('Value'), max_length=1, choices=ECG_VALUES)
    max_evaluation = models.IntegerField(_('Max Evaluation'),
                                            help_text=_('Only for an indicator, without a parent.'),
                                            null=True,
                                            blank=True)

    parent = models.ForeignKey('ecg_balancing.Indicator', verbose_name=_(u'Parent Indicator'), related_name='parent_indicator',
                              null=True,
                              blank=True)
    subindicator_number = models.IntegerField(_('Subindicator Number'),
                                                help_text=_('Only for a subindicator, an indicator with a parent.'),
                                                null=True,
                                                blank=True)
    relevance = models.CharField(_('Relevance'), max_length=10, choices=RELEVANCE_VALUES, default=RELEVANCE_MIDDLE, 
                                        help_text=_('Only for a subindicator, an indicator with a parent.'),
                                                null=True,
                                                blank=True)
    sole_proprietorship = models.BooleanField(_('Applicable for sole proprietorship?'), default=True)


    editor = models.CharField(_('Editor'),  max_length=30, blank=True, null=True)
    contact = fields.CommaSeparatedEmailField(_('Email(s)'),
                                              help_text=_('Multiple emails should be separated with a comma'),
                                              max_length=255, blank=True, null=True)

    description = RichTextField(_('Target questions'), blank=True, null=True)
    key_figures = RichTextField(_('Key figures'), blank=True, null=True)
    evaluation_table = RichTextField(_('Evaluation table'), blank=True, null=True)

    class Meta:
        verbose_name = _('Indicator')
        verbose_name_plural = _('Indicators')

    def __unicode__(self):
        if self.stakeholder.startswith('n'):
            return '%s%s' % (
                unicode(self.stakeholder),
                unicode(self.subindicator_number)
            )
        elif self.parent is None:
            return '%s%s' % (
                unicode(self.stakeholder),
                unicode(self.ecg_value)
            )
        else:
            return '%s%s.%s' % (
                unicode(self.stakeholder),
                unicode(self.ecg_value),
                unicode(self.subindicator_number)
            )

    def slugify(self):
        if self.stakeholder.startswith('n'):
            return '%s%s' % (
                unicode(self.stakeholder),
                unicode(self.subindicator_number)
            )
        elif self.parent is None:
            return '%s%s' % (
                unicode(self.stakeholder),
                unicode(self.ecg_value)
            )
        else:
            return '%s%s-%s' % (
                unicode(self.stakeholder),
                unicode(self.ecg_value),
                unicode(self.subindicator_number)
            )


# -------------------------------- COMPANY MODELS --------------------------------


class Company(models.Model):

    INDUSTRY_CHOICE_CONSTRUCTION = 'construction'
    INDUSTRY_CHOICE_MINING_AND_QUARRYING = 'mining_and_quarrying'
    INDUSTRY_CHOICE_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_SERVICE_ACTIVITIES = 'professional_scientific_and_technical_service_activities'
    INDUSTRY_CHOICE_OTHER_SERVICE_ACTIVITIES = 'other_service_activities'
    INDUSTRY_CHOICE_ADMINISTRATIVE_AND_SUPPORT_SERVICE_ACTIVITIES = 'administrative_and_support_service_activities'
    INDUSTRY_CHOICE_ELECTRICITY_GAS_STEAM_AND_AIR_CONDITIONING_SUPPLY = 'electricity_gas_steam_and_air_conditioning_supply'
    INDUSTRY_CHOICE_EDUCATION = 'education'
    INDUSTRY_CHOICE_ACTIVITIES_OF_EXTRATERRITORIAL_ORGANISATIONS_AND_BODIES = 'activities_of_extraterritorial_organisations_and_bodies'
    INDUSTRY_CHOICE_FINANCIAL_AND_INSURANCE_ACTIVITIES = 'financial_and_insurance_activities'
    INDUSTRY_CHOICE_RESEARCH_AND_DEVELOPMENT = 'research_and_development'
    INDUSTRY_CHOICE_GARDENERS_AND_FLORISTS = 'gardeners_and_florists'
    INDUSTRY_CHOICE_HUMAN_HEALTH_AND_SOCIAL_WORK_ACTIVITIES = 'human_health_and_social_work_activities'
    INDUSTRY_CHOICE_WHOLESALE_AND_RETAIL_TRADE_REPAIR_OF_MOTOR_VEHICLES_AND_MOTORCYCLES = 'wholesale_and_retail_trade_repair_of_motor_vehicles_and_motorcycles'
    INDUSTRY_CHOICE_REAL_ESTATE_ACTIVITIES = 'real_estate_activities'
    INDUSTRY_CHOICE_OTHER_INDUSTRIES = 'other_industries'
    INDUSTRY_CHOICE_CHARITABLE_ORGANIZATIONS_NGO = 'charitable_organizations_ngo'
    INDUSTRY_CHOICE_CHURCH_AND_RELIGIOUS_INSTITUTIONS = 'church_and_religious_institutions'
    INDUSTRY_CHOICE_ART_AND_CULTURE = 'art_and_culture'
    INDUSTRY_CHOICE_AGRICULTURE_FORESTRY_AND_FISHING = 'agriculture_forestry_and_fishing'
    INDUSTRY_CHOICE_FOOD_INDUSTRIES = 'food_industries'
    INDUSTRY_CHOICE_MEDIA_MANAGEMENT_ADVERTISING_AND_MARKET_COMMUNICATION = 'media_management_advertising_and_market_communication'
    INDUSTRY_CHOICE_METAL_AND_ELECTRICAL_INDUSTRY = 'metal_and_electrical_industry'
    INDUSTRY_CHOICE_PUBLIC_ADMINISTRATION_AND_DEFENCE_COMPULSORY_SOCIAL_SECURITY = 'public_administration_and_defence_compulsory_social_security'
    INDUSTRY_CHOICE_POLITICS_POLITICAL_ACTIONS = 'politics_political_actions'
    INDUSTRY_CHOICE_ACTIVITIES_OF_HOUSEHOLDS_AS_EMPLOYERS = 'activities_of_households_as_employers'
    INDUSTRY_CHOICE_LAW_LAWYER_TAX_CONSULTANCY = 'law_lawyer_tax_consultancy'
    INDUSTRY_CHOICE_TEXTILES_CLOTHING_SHOE_AND_LEATHER_INDUSTRY = 'textiles_clothing_shoe_and_leather_industry'
    INDUSTRY_CHOICE_ACCOMMODATION_AND_FOOD_SERVICE_ACTIVITIES = 'accommodation_and_food_service_activities'
    INDUSTRY_CHOICE_TRANSPORTATION_AND_STORAGE = 'transportation_and_storage'
    INDUSTRY_CHOICE_CONSULTING_AND_IT_INDUSTRY = 'consulting_and_it_industry'
    INDUSTRY_CHOICE_MANUFACTURING = 'manufacturing'
    INDUSTRY_CHOICE_WATER_SUPPLY_SEWERAGE_WASTE_MANAGEMENT_AND_REMEDIATION_ACTIVITIES = 'water_supply_sewerage_waste_management_and_remediation_activities'
    
    INDUSTRY_CHOICES = (
        (INDUSTRY_CHOICE_CONSTRUCTION, _('Construction')),
        (INDUSTRY_CHOICE_MINING_AND_QUARRYING, _('Mining and quarrying')),
        (INDUSTRY_CHOICE_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_SERVICE_ACTIVITIES, _('Professional, scientific and technical service activities')),
        (INDUSTRY_CHOICE_OTHER_SERVICE_ACTIVITIES, _('Other service activities')),
        (INDUSTRY_CHOICE_ADMINISTRATIVE_AND_SUPPORT_SERVICE_ACTIVITIES, _('Administrative and support service activities')),
        (INDUSTRY_CHOICE_ELECTRICITY_GAS_STEAM_AND_AIR_CONDITIONING_SUPPLY, _('Electricity, gas, steam and air conditioning supply')),
        (INDUSTRY_CHOICE_EDUCATION, _('Education')),
        (INDUSTRY_CHOICE_ACTIVITIES_OF_EXTRATERRITORIAL_ORGANISATIONS_AND_BODIES, _('Activities of extraterritorial organisations and bodies')),
        (INDUSTRY_CHOICE_FINANCIAL_AND_INSURANCE_ACTIVITIES, _('Financial and insurance activities')),
        (INDUSTRY_CHOICE_RESEARCH_AND_DEVELOPMENT, _('Research and development')),
        (INDUSTRY_CHOICE_GARDENERS_AND_FLORISTS, _('Gardeners and florists')),

ecg_balancing/templates/ecg_balancing/company_balance_export.html
{% load i18n cms_tags menu_tags sekizai_tags static %}
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:site_name" content="{% trans "ECG Balancing" %}"/>
  <meta property="og:title"
        content="{% if request.current_page.get_menu_title %} &raquo; {{ request.current_page.get_menu_title }}{% endif %}"/>
  <meta property="og:description" content=""/>

  <meta name="viewport" content="width=device-width, initial-scale=1"/>

  <title>Export - {% trans "ECG Balance" %} {{ company }}</title>

  <link rel="icon" href="{% static 'images/ecg-seeds_30h.png' %}"/>
  <!-- <script type="text/javascript" src="{% static 'js/vendor/jquery.min.js' %}"></script> -->

  <link href="{% static 'css/bootstrap3-ecg.css' %}" rel="stylesheet">
  <!--[if IE]>
  <link href="{% static 'css/ie.css' %}" media="screen, projection" rel="stylesheet" type="text/css"/>
  <![endif]-->

  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link href="{% static 'ecg_balancing/css/company_balance_export.css' %}" rel="stylesheet">

  <style>
    .ecg-green {
      color: #cccb98;
    }

    .balance-export h1, h2, h3, h4, h5 {
      margin-top: 1.5em;
    }

    .align-right {
      text-align: right !important;
    }

    .balance-export table, .balance-export tr {
      width: 100%;
      vertical-align: top;
      text-align: left;
      border-collapse: collapse;
      border-bottom: 1px solid #ddd;
    }

    .balance-export table:last-child, .balance-export tr:last-child {
      border: none;
    }

    .balance-export th, .balance-export td {
      padding: .5em;
      vertical-align: top;
      text-align: left;
    }

    .company-general th, .company-activities th, .process-description th {
      text-align: left;
      width: 25%;
    }

    .subindicator-title {
      font-weight: bold;
    }

    .company-commongood, .evaluation-table, .key-figures, .target-questions, .prospect {
      width: 100%;
    }

    .evaluation-table table, .evaluation-table tr,
    .key-figures table, .key-figures tr,
    .target-questions table, .target-questions tr {
      width: 100% !important;
    }

    .evaluation-table th, .evaluation-table td,
    .key-figures th, .key-figures td,
    .key-figures th, .key-figures td {
      border: 1px solid #ddd;
      padding: 0.125em .5em !important;
      vertical-align: top !important;
      text-align: left !important;
    }

    .timestamp {
      margin-top: 5em;
      color: gray;
      border-bottom: 1px solid gray;
    }
  </style>
</head>

<body class="{% block body_class %}{% endblock body_class %}">
  <div id="wrap">
    <div class="container site-container">
      <h1 class="indicator-page-title center ecg-green">
        {% trans 'ECG Balance' %} {{ company }}
      </h1>

      <div class="balance-export">
        {% if has_company_access or not visibility_basic %}

          <h2 class="ecg-green">{% trans "Company" %}</h2>
          <div class="company-general">
            <h3 class="ecg-green">{% trans "General Informations" %}</h3>
            <table>
              <tr>
                <th>{% trans "Company name" %}:</th>
                <td>{% if company.name %}{{ company.name }}{% endif %}</td>
              </tr>
              <tr>
                <th>{% trans "Eigentums- und Rechtsform, Eigentumsanteile" %}:</th>
                <td></td>
              </tr>
              <tr>
                <th>{% trans "Industry" %}:</th>
                <td>{% if company.industry %}{{ company.get_industry_display }}{% endif %}</td>
              </tr>
              <tr>
                <th>{% trans "Number of employees" %}:</th>
                <td>{% if balance.get_employees_number_display %}{{ balance.get_employees_number_display }}{% endif %}</td>
              </tr>
              <tr>
                <th>{% trans "Revenue" %}:</th>
                <td>{% if balance.revenue %}{{ balance.revenue }} €{% endif %}</td>
              </tr>
              <tr>
                <th>{% trans "Profit" %}:</th>
                <td>{% if balance.profit %}{{ balance.profit }} €{% endif %}</td>
              </tr>
              <!--<tr>
                <th>{% trans "Peer companies" %}:</th>
                <td>
                  {% for peer_company in balance.peer_companies.all %}
                    &bull; {{ peer_company.name }}<br />
                  {% endfor %}
              </tr>-->
              <tr>
                <th>{% trans "Affiliates" %}:</th>
                <td>
                  {% if company.affiliates %}{{ company.affiliates }}{% endif %}
              </tr>
              <tr>
                <th>{% trans "Office and Homepage" %}:</th>
                <td>{{ company.name }}<br />
                    {{ company.street }}<br />
                    {{ company.zipcode }} {{ company.city }}<br />
                    {{ company.country }}<br />
                    <span class="glyphicon glyphicon-link glyphicon-greyer"></span>
                    <a href="{{ company.website }}">{{ company.website }}</a><br/>
                </td>
              </tr>
              <tr>
                <th>{% trans "Balance period" %}:</th>
                <td>{{ balance.start_date }} &ndash; {{ balance.end_date }}</td>
              </tr>
            </table>
          </div>

          <h3 class="ecg-green">{% trans "Area of activity" %}</h3>
          <div class="company-activities">
            <table>
              <tr>
                <th>{% trans "Company introduction" %}:</th>
                <td></td>
              </tr>
              <tr>
                <th>{% trans "Activities" %}:</th>
                <td>{% if company.activities %}{{ company.activities }}{% endif %}</td>
              </tr>
              <tr>
                <th>{% trans "Products and Services" %}:</th>
                <td></td>
              </tr>
            </table>
          </div>

          <h3 class="ecg-green">{% trans "The Company and Common Good" %}</h3>
          <div class="company-commongood">
            {{ balance.common_good|safe }}
          </div>

          <h2 class="ecg-green">{% trans "Self-assessment and attestation" %}</h2>
          <div class="company-selfassessment">
            <table>
              <tr>
                <th></th>
                <th>{% trans "Indicator" %}</th>
                <th class="align-right">{% trans "Self-assessment" %}</th>
              </tr>
              {% for indicator in indicators %}
                <tr>
                  <td>{{ indicator.indicator|upper }}</td>
                  <td>{{ indicator.indicator.title }}</td>
                  <td class="align-right">{{ indicator.evaluation }} / {{ indicator.indicator.max_evaluation }}</td>
                </tr>
              {% endfor %}
            </table>
          </div>

          <h2 class="ecg-green">{% trans "Negative Criteria" %}</h2>
          <div class="negative-criteria">
            <table>
              <tr>
                <th>{% trans "Negative criteria" %}</th>
                <th class="align-right">Bewertung</span></th>
              </tr>
              {% for negative_indicator in negative_indicators %}
                <tr>
                  <td>{{ negative_indicator.indicator.title }}</td>
                  <td class="align-right">{{ negative_indicator.evaluation }} / {{ negative_indicator.indicator.max_evaluation }}</td>
                </tr>
              {% endfor %}
            </table>
          </div>

          <h2 class="ecg-green">{% trans "Detailed description of each criteria" %}</h2>
          <div class="detailed-criteria">
            {% for indicator in indicators %}

              <h3 class="ecg-green">{{ indicator.indicator|upper }} {{ indicator.indicator.title }}</h3>

              {% if indicator.description %}
                <div class="criteria-description">
                  {{ indicator.description|safe }}
                </div>
              {% endif %}

              {% for subindicator in subindicators %}
                {% if subindicator.indicator.parent == indicator.indicator %}

                  <h4 class="subindicator-title">{{ subindicator.indicator|upper }} {{ subindicator.indicator.title }} ({% trans "Relevance" %}: {{ subindicator.indicator.get_relevance_display|lower }})</h4>

                  {% if subindicator.evaluation_table %}
                    <h4 class="ecg-green">{% trans "Evaluation table" %}</h4>
                    <div class="evaluation-table">
                      {{ subindicator.evaluation_table|safe }}
                    </div>
                  {% endif %}

                  {% if subindicator.key_figures %}
                    <h4 class="ecg-green">{% trans "Key figures" %}</h4>
                    <div class="key-figures">
                      {{ subindicator.key_figures|safe }}
                    </div>
                  {% endif %}

                  {% if subindicator.description %}
                    <h4 class="ecg-green">{% trans "Target questions" %}</h4>
                    <div class="target-questions">
                      {{ subindicator.description|safe }}
                    </div>
                  {% endif %}

                {% endif %}
              {% endfor %}

            {% endfor %}
          </div>

          <h2 class="ecg-green">{% trans "Prospect" %}</h2>
          <div class="prospect">
            {{ balance.prospect|safe }}
          </div>

          <h2 class="ecg-green">{% trans "Balance process description" %}</h2>
          <div class="process-description">
            <p>{{ balance.process_description|safe}}</p>

            <table>
              <!-- <tr>
                <th>{% trans "Participated Stakeholders" %}</th>
                <td>{{ balance.updated_by }}</td>
              </tr> -->
              <tr>
                <th>{% trans "Number of participated employees" %}</th>
                <td>{{ balance.number_participated_employees }} {% trans "Employees" %}</td>
              </tr>
              <tr>
                <th>{% trans "Worked Hours" %}</th>
                <td>{{ balance.worked_hours }} {% trans "Hours" %}</td>
              </tr>
              <tr>
                <th>{% trans "How was the balance internally communicated?" %}</th>
                <td>{{ balance.internal_communication|safe }}</td>
              </tr>
            </table>
          </div>

        {% endif %}
      </div>

      <p class="timestamp">{% trans "Date" %}: {% now "SHORT_DATETIME_FORMAT" %}</p>
    </div>
  </div>
</body>
</html>

ecg_balancing/templates/ecg_balancing/company_no_balance.html
{% extends "base.html" %}
{% load i18n cms_tags menu_tags sekizai_tags thumbnail %}
{% load static from staticfiles %}

{% block page_title %}{% trans 'No Access' %}{% endblock %}

{% block base_content %}

  {{ company_name }} {% trans "does not have an ECG Balance for this year." %}

{% endblock base_content %}

ecg_balancing/templates/ecg_balancing/feedback_indicator_success.html
{% extends "base.html" %}
{% load i18n cms_tags menu_tags sekizai_tags thumbnail crispy_forms_tags %}
{% load static from staticfiles %}

{% block page_title %}{% trans "Send Indicator Feedback" %}{% endblock %}

{% block base_content %}

  {% trans "Thank You! Your feedback has been sent to the ECG editors team." %}
  <br/>
  <br/>

  <a href="{{ request.GET.url }}" class="btn btn-default">
    <span class="glyphicon glyphicon-chevron-left"></span>
    {% trans "Back to ECG Balance" %}
  </a>

{% endblock base_content %}